# Generated by Django 5.0.6 on 2024-08-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_bio'),
        ('account', '0006_user_posts_count'),
    ]

    operations = [
    ]
